### ISSUE TITLE
Refactor Sass classes from more generic elements to less

### ISSUE THREAD

**Issue by joseigor** [jkiot/plantcare-webapp#10]
As a more general rule I think the first elements of a class should be the ones that define the container shape  and  then more specific elements, so for this class  I would say a order would be:
```css
&-table {
display: flex;
flex-direction: column;
height: 50rem;
border-radius: 10px;
align-items: center;
background-color: #fff;
overflow: hidden;
transition: all 0.2s;
 box-shadow: 0 1rem 1rem rgba(0, 0, 0, 0.158);
}
```

This is a suggestion but I think you can get the idea. I have created a followup issue to do this refactor so you do not need to do this refactor as part for this pull request. See
